import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { ChakraProvider } from "@chakra-ui/react";
import Footer from "@/components/Footer/Footer";
import { Params } from "next/dist/shared/lib/router/utils/route-matcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {  

  return (
    <html lang="uk">
      
        <body className={inter.className}>
        
        <ChakraProvider>
          <Header
            params={params}
          />
          <main>
            {children}
          </main>
          <Footer params={params}/>
        </ChakraProvider>
        </body>
      
    </html>
  );
}
